Repository antvis/component, pull requests merged in 2019-10, with the labels that each got.

#74 Daily 1118
  package.json
  src/abstract/component.ts
  src/abstract/group-component.ts
  src/abstract/html-component.ts
  src/axis/base.ts
  src/axis/circle.ts
  src/axis/line.ts
  src/grid/base.ts
  src/legend/category.ts
  src/legend/continue.ts
  src/types.ts
  src/util/matrix.ts
  src/util/util.ts
  tests/unit/legend/category-spec.ts
Labels: PR: reviewed-approved

#75 feat: add getBBox method for group-component
  package.json
  src/abstract/group-component.ts
  src/axis/circle.ts
  src/axis/index.ts
  src/axis/line.ts
  src/index.ts
  src/legend/index.ts
Labels: PR: reviewed-changes-requested, enhancement

#76 Daily 1123
  package.json
  src/abstract/component.ts
  src/abstract/group-component.ts
  src/abstract/html-component.ts
  src/intefaces.ts
  src/legend/category.ts
  src/tooltip/css-const.ts
  src/tooltip/html-theme.ts
  src/tooltip/html.ts
  src/types.ts
  src/util/align.ts
  src/util/matrix.ts
  src/util/util.ts
  tests/unit/component/component-spec.ts
  tests/unit/component/group-simple-spec.ts
  tests/unit/component/html-component-spec.ts
  tests/unit/tooltip/html-spec.ts
  tests/unit/util-spec.ts
Labels: PR: unreviewed

#77 feat(legend): add legend and check unused locals
  src/abstract/component.ts
  src/abstract/group-component.ts
  src/axis/base.ts
  src/axis/circle.ts
  src/axis/line.ts
  src/grid/base.ts
  src/grid/circle.ts
  src/grid/line.ts
  src/intefaces.ts
  src/legend/base.ts
  src/legend/category.ts
  src/legend/continue.ts
  src/legend/size.ts
  src/legend/table.ts
  src/tooltip/html.ts
  src/types.ts
  src/util/align.ts
  src/util/matrix.ts
  src/util/theme.ts
  src/util/util.ts
  tests/unit/axis/line-spec.ts
  tests/unit/component/component-spec.ts
  tests/unit/component/group-simple-spec.ts
  tests/unit/component/group-spec.ts
  tests/unit/legend/category-spec.ts
  tests/unit/legend/continue-spec.ts
  tests/unit/tooltip/html-spec.ts
  tsconfig.json
Labels: PR: unreviewed
