Repository antvis/component, pull requests merged in 2019-09, with the labels that each got.

#65 Fix enterable invalid
  package.json
  src/tooltip/mixin/position.js
Labels: PR: reviewed-changes-requested

#66 add size-plugin
  .travis.yml
  package.json
  size-plugin.json
  webpack-dev.config.js
  webpack.config.js
Labels: PR: unreviewed

#64 fix(tooltip): fix position property when use htmlContent for tooltip
  src/tooltip/html.js
Labels: PR: reviewed-changes-requested, bug

#67 feat(bug): fixed bug of invalid position for guide, component destroy…
  size-plugin.json
  src/axis/base.js
  src/component.js
  src/guide/arc.js
  src/guide/base.js
  src/guide/data-marker.js
  src/guide/data-region.js
  src/guide/html.js
  src/guide/image.js
  src/guide/line.js
  src/guide/region.js
  src/guide/text.js
  src/label/base.js
  src/legend/base.js
  src/legend/cat-html.js
  src/legend/cat-page-html.js
  src/tooltip/base.js
  test/unit/guide/arc-spec.js
  test/unit/guide/base-spec.js
  test/unit/guide/data-marker-spec.js
  test/unit/guide/data-region-spec.js
  test/unit/guide/html-spec.js
  test/unit/guide/image-spec.js
  test/unit/guide/line-spec.js
  test/unit/guide/region-spec.js
  test/unit/guide/text-spec.js
  test/unit/label/label-base-spec.js
  test/unit/tooltip/canvas-spec.js
Labels: PR: reviewed-approved, enhancement

#69 fix: revert #66
  .travis.yml
  package.json
  size-plugin.json
  webpack-dev.config.js
  webpack.config.js
Labels: PR: unreviewed, bug

#68 Fix label html container leak
  package.json
  src/label/base.js
  test/bugs/issue-g2-1213-spec.js
Labels: PR: reviewed-approved

#70 fix(legend): insert legend page flip to right contianer
  src/legend/cat-page-html.js
Labels: PR: reviewed-changes-requested, bug

#71 feat(version): update version and add the judgment of show/hide for t…
  package.json
  src/tooltip/html.js
Labels: PR: reviewed-changes-requested, enhancement

#72 Fix tooltip
  package.json
  src/tooltip/html.js
  src/tooltip/mixin/marker-group.js
Labels: PR: reviewed-changes-requested
