Repository antvis/component, pull requests merged in 2019-12, with the labels that each got.

#106 feat(legend): support category legend flip page
  .github/workflows/ci.yml
  package.json
  src/abstract/group-component.ts
  src/legend/category.ts
  src/util/matrix.ts
  src/util/theme.ts
  src/util/util.ts
  tests/unit/legend/category-spec.ts
Labels: PR: unreviewed, enhancement

#108 fix: 修复分类图例翻页器在update过程的渲染
  src/legend/category.ts
  tests/unit/legend/category-spec.ts
Labels: PR: reviewed-approved, bug

#110 Delegation emit
  package.json
  src/abstract/component.ts
  src/abstract/group-component.ts
  src/axis/base.ts
  src/legend/category.ts
  src/legend/continuous.ts
  src/types.ts
  src/util/event.ts
  tests/unit/component/component-spec.ts
  tests/unit/component/group-simple-spec.ts
  tests/unit/legend/continuous-spec.ts
  tests/unit/legend/legend-animate-spec.ts
Labels: PR: reviewed-approved

#111 fix(update): copy element error
  package.json
  src/abstract/group-component.ts
  tests/unit/legend/category-spec.ts
Labels: PR: reviewed-approved, bug

#112 fix(legend): clip track
  package.json
  src/abstract/group-component.ts
  src/legend/continuous.ts
  src/util/event.ts
  tests/unit/legend/continuous-spec.ts
Labels: PR: reviewed-approved, bug

#114 fix: typo
  src/types.ts
Labels: PR: reviewed-approved, bug

#115 refactor: 配合 G2 改造，shape.getMarker() 将样式都存储在 style 属性中
  src/legend/category.ts
  tests/unit/legend/category-spec.ts
Labels: PR: reviewed-approved, refactor

#116 Update version
  package.json
Labels: PR: reviewed-approved

#117 feat(types): change type definition
  package.json
  src/types.ts
  tests/unit/util-spec.ts
Labels: PR: reviewed-approved, enhancement

#118 feat: 添加slider和scrollbar组件
  package.json
  src/abstract/group-component.ts
  src/annotation/arc.ts
  src/annotation/image.ts
  src/annotation/line.ts
  src/annotation/region.ts
  src/annotation/text.ts
  src/axis/base.ts
  src/axis/line.ts
  src/axis/overlap/auto-ellipsis.ts
  src/axis/overlap/auto-hide.ts
  src/axis/overlap/auto-rotate.ts
  src/crosshair/base.ts
  src/grid/base.ts
  src/interfaces.ts
  src/legend/base.ts
  src/legend/category.ts
  src/legend/continuous.ts
  src/scrollbar/scrollbar.ts
  src/slider/constant.ts
  src/slider/handler.ts
  src/slider/slider.ts
  src/trend/constant.ts
  src/trend/path.ts
  src/trend/trend.ts
  src/types.ts
  src/util/event.ts
  src/util/label.ts
  tests/unit/scrollbar/scrollbar-spec.ts
  tests/unit/slider/slider-spec.ts
  tests/unit/trend/constant.ts
  tests/unit/trend/trend-spec.ts
  tests/util/simulate.ts
  tsconfig.json
Labels: PR: reviewed-approved, enhancement
