Repository antvis/component, pull requests merged in 2020-10, with the labels that each got.

#194 fix(axis): when line, label all is null
  package.json
  src/util/util.ts
  tests/unit/axis/empty-line-spec.ts
Labels: PR: unreviewed, bug

#195 fix(types): Update AxisTitleCfg
  src/types.ts
Labels: PR: reviewed-approved, bug

#197 fix(#196): when on autoEllipsis = true
  src/axis/line.ts
  src/axis/overlap/auto-ellipsis.ts
  src/legend/category.ts
  src/util/graphic.ts
  src/util/label.ts
  tests/bugs/issue-196-spec.ts
Labels: PR: partially-approved, bug

#198 chore: v0.7.6
  package.json
Labels: PR: unreviewed, chore

#199 fix(ellipsis): 因为方向问题,导致计算出来的 limitLength 为负数,导致判断错误
  package.json
  src/axis/overlap/auto-ellipsis.ts
  tests/bugs/issue-196-spec.ts
Labels: PR: reviewed-approved, bug

#201 fix(axis): label style 回调的参数应该是调整完后的值
  src/axis/base.ts
  tests/bugs/issue-axis-style-callback.ts
Labels: PR: reviewed-approved, bug

#200 revert: auto ellipsis
  src/axis/line.ts
  src/axis/overlap/auto-ellipsis.ts
  src/legend/category.ts
  src/util/graphic.ts
  src/util/label.ts
  tests/bugs/issue-196-spec.ts
Labels: PR: unreviewed, revert

#202 feat: 支持自定义shape annotation 和 html annotation
  package.json
  src/abstract/group-component.ts
  src/annotation/html.ts
  src/annotation/index.ts
  src/annotation/shape.ts
  src/axis/base.ts
  src/types.ts
  tests/unit/annotation/html-spec.ts
  tests/unit/annotation/shape-spec.ts
  tests/unit/axis/line-spec.ts
Labels: PR: unreviewed, enhancement
