Repository antvis/component, pull requests merged in 2020-12, with the labels that each got.

#209 chore: add src to files for sourceMap
  package.json
Labels: PR: unreviewed

#210 feat: 日常发布
  CHANGELOG.md
  package.json
Labels: PR: reviewed-approved

#211 fix: 图例在设置 offset 的时候 getLayoutBBox 的 width height 不正确
  src/legend/base.ts
  tests/bugs/issue-g2-2921-spec.ts
  tests/unit/annotation/text-spec.ts
Labels: PR: partially-approved

#212 fix(esm): remove all the lib import
  package.json
  src/index.ts
  src/util/event.ts
Labels: PR: unreviewed

#213 fix: 修复 Axis Title offset 的自动计算逻辑
  src/axis/line.ts
  tests/unit/axis/auto-title-spec.ts
Labels: PR: unreviewed

#215 fix: use typescript syntax
  package.json
  src/index.ts
Labels: PR: partially-approved
