Repository antvis/component, pull requests merged in 2020-02, with the labels that each got.

#129 Update no render
  package.json
  src/abstract/component.ts
  src/abstract/group-component.ts
  src/abstract/html-component.ts
  src/axis/line.ts
  src/interfaces.ts
  src/legend/category.ts
  src/scrollbar/scrollbar.ts
  src/slider/handler.ts
  src/slider/slider.ts
  src/types.ts
  src/util/matrix.ts
  tests/bugs/issue-legend-spec.ts
  tests/unit/annotation/arc-spec.ts
  tests/unit/annotation/data-marker-spec.ts
  tests/unit/annotation/data-region-spec.ts
  tests/unit/annotation/image-spec.ts
  tests/unit/annotation/line-spec.ts
  tests/unit/annotation/region-filter-spec.ts
  tests/unit/annotation/region-spec.ts
  tests/unit/annotation/text-spec.ts
  tests/unit/axis/circle-spec.ts
  tests/unit/axis/line-spec.ts
  tests/unit/component/component-spec.ts
  tests/unit/component/group-simple-spec.ts
  tests/unit/component/group-spec.ts
  tests/unit/component/html-component-spec.ts
  tests/unit/crosshair/circle-spec.ts
  tests/unit/crosshair/line-spec.ts
  tests/unit/grid/circle-spec.ts
  tests/unit/grid/line-spec.ts
  tests/unit/legend/category-spec.ts
  tests/unit/legend/continuous-spec.ts
  tests/unit/legend/legend-animate-spec.ts
  tests/unit/scrollbar/scrollbar-spec.ts
  tests/unit/slider/slider-spec.ts
  tests/unit/tooltip/html-spec.ts
  tests/unit/trend/trend-spec.ts
Labels: PR: unreviewed

#131 feat(continuous): drag track
  src/legend/continuous.ts
  tests/unit/legend/continuous-spec.ts
Labels: PR: unreviewed, enhancement

#130 fix: do not set clip for legend when flipPage is false
  src/legend/category.ts
Labels: PR: reviewed-approved, bug

#132 fix: data region cfg option update
  src/annotation/data-region.ts
  tests/unit/annotation/data-region-spec.ts
Labels: PR: reviewed-approved, bug

#133 chore: 0.5.0-beta.25
  package.json
Labels: PR: unreviewed, chore

#134 feat: 图例翻页样式 & regionFilter单测
  src/legend/category.ts
  tests/unit/annotation/region-filter-spec.ts
  tests/unit/legend/category-spec.ts
Labels: PR: unreviewed, enhancement

#135 Animate params
  package.json
  src/abstract/component.ts
Labels: PR: reviewed-changes-requested

#137 fix: 修复slider在render之前的update报错
  src/abstract/group-component.ts
  src/slider/slider.ts
  tests/unit/slider/slider-spec.ts
Labels: PR: unreviewed, bug

#140 feat(clip): update clip
  src/abstract/group-component.ts
  src/legend/continuous.ts
  src/util/util.ts
  tests/unit/group-util-spec.ts
  tests/unit/util-spec.ts
Labels: enhancement

#141 fix: set clip on off-screen group for category legend
  package.json
  src/abstract/group-component.ts
  src/annotation/region-filter.ts
  src/legend/category.ts
  src/trend/path.ts
  tests/unit/legend/category-spec.ts
Labels: bug

#143 fix: correct category legend clip & navigation state
  src/legend/category.ts
  tests/unit/legend/category-spec.ts
  tests/unit/legend/legend-animate-spec.ts
Labels: bug

#145 feat(version): 0.5.0
  package.json
Labels: enhancement
