Repository antvis/component, pull requests merged in 2020-05, with the labels that each got.

#160 feat: 支持html-tooltip的htmlContent
  src/tooltip/html-theme.ts
  src/tooltip/html.ts
  tests/unit/tooltip/html-spec.ts
Labels: PR: unreviewed, enhancement

#162 fix(axis): 修复 subTickLine style 属性无法生效的问题
  src/axis/base.ts
  tests/unit/axis/line-spec.ts
Labels: PR: partially-approved, bug

#163 fix(axis): 修复坐标轴 title offset 无法生效的问题
  src/axis/base.ts
  src/axis/line.ts
  tests/unit/axis/circle-spec.ts
  tests/unit/axis/line-spec.ts
Labels: PR: partially-approved, bug

#161 fix: set clip on each legend item
  package.json
  src/legend/category.ts
  tests/unit/legend/category-spec.ts
Labels: PR: unreviewed, bug

#164 chore: bump version to 0.5.7
  package.json
Labels: PR: unreviewed, chore

#165 升级 @antv/matrix-util
  package.json
  src/axis/base.ts
  src/axis/circle.ts
  src/axis/line.ts
  src/util/matrix.ts
Labels: PR: unreviewed

#167 fix: axis title offset without label
  package.json
  src/axis/base.ts
  src/types.ts
  tests/bugs/issue-axis-title-spec.ts
Labels: PR: unreviewed, bug

#169 add responsive method
  package.json
  src/axis/overlap/auto-ellipsis-time.ts
  src/axis/overlap/auto-ellipsis.ts
  src/axis/overlap/auto-format.ts
  src/axis/overlap/auto-wrap.ts
  src/axis/overlap/util.ts
  src/legend/responsive.ts
  src/util/text.ts
  tests/unit/axis/auto-format-spec.ts
  tests/unit/axis/auto-wrap-spec.ts
Labels: PR: partially-approved

#170 fix: tooltip 自动位置时的冲出边缘位置调整
  package.json
  src/util/align.ts
  tests/unit/tooltip/html-spec.ts
Labels: PR: partially-approved, bug
