Repository antvis/component, pull requests merged in 2020-04, with the labels that each got.

#156 feat: 判断tooltip的listDom节点是否存在
  src/abstract/component.ts
  src/annotation/text.ts
  src/legend/category.ts
  src/legend/continuous.ts
  src/tooltip/html.ts
  src/util/align.ts
  src/util/matrix.ts
  src/util/util.ts
  tests/unit/group-util-spec.ts
  tests/unit/util-spec.ts
Labels: PR: reviewed-approved, enhancement

#150 Html crosshair
  README.md
  package.json
  src/abstract/component.ts
  src/abstract/group-component.ts
  src/abstract/html-component.ts
  src/crosshair/css-const.ts
  src/crosshair/html-theme.ts
  src/crosshair/html.ts
  src/crosshair/index.ts
  src/crosshair/line.ts
  src/tooltip/html.ts
  src/types.ts
  src/util/util.ts
  tests/unit/component/group-spec.ts
  tests/unit/component/html-component-spec.ts
  tests/unit/crosshair/html-spec.ts
Labels: PR: reviewed-approved

#158 chore: update version to 0.5.5
  package.json
Labels: PR: reviewed-approved, chore

#157 fix: unit test for scrollbar and slider
  src/scrollbar/scrollbar.ts
  src/slider/constant.ts
  src/slider/slider.ts
  tests/unit/scrollbar/scrollbar-spec.ts
  tests/unit/slider/handler-spec.ts
  tests/unit/slider/slider-spec.ts
  tests/util/simulate.ts
Labels: PR: reviewed-approved, bug
