Repository antvis/component, pull requests merged in 2020-08, with the labels that each got.

#182 feat(version): update to 0.7.0
  package.json
Labels: PR: reviewed-approved, enhancement

#183 fix: removeDom 节点不一定有parentNode
  src/abstract/html-component.ts
Labels: bug

#187 feat(axis): add label, grid, tickLine style callback typedefine
  src/axis/base.ts
  src/grid/base.ts
  src/types.ts
  tests/bugs/issue-188-spec.ts
Labels: enhancement

#189 fix(slider): slider 更新的时候,组合的子组件不更新的问题
  src/slider/slider.ts
  tests/unit/slider/slider-spec.ts
Labels: bug
