Repository antvis/component, pull requests merged in 2020-01, with the labels that each got.

#119 build: release 0.5.0-beta.17
  package.json
Labels: PR: reviewed-approved, build

#121 feat: annotation组件dataMarker dataRegion RegionFilter
  package.json
  src/annotation/data-marker.ts
  src/annotation/data-region.ts
  src/annotation/index.ts
  src/annotation/region-filter.ts
  src/types.ts
  src/util/util.ts
  tests/unit/annotation/data-marker-spec.ts
  tests/unit/annotation/data-region-spec.ts
  tests/unit/annotation/region-filter-spec.ts
  tests/util/dom.ts
Labels: PR: unreviewed, enhancement

#123 chore: 参数可选
  src/types.ts
Labels: PR: reviewed-changes-requested, chore

#124 fix: textBackground can be set null
  src/crosshair/base.ts
  tests/unit/crosshair/circle-spec.ts
Labels: PR: unreviewed, bug

#126 Fix types
  src/types.ts
Labels: PR: reviewed-approved
