Repository antvis/component, pull requests merged in 2020-03, with the labels that each got.

#146 chore: add missing path-utils dep
  package.json
Labels: PR: unreviewed, chore

#147 feat(tooltip): tooltip position auto
  package.json
  src/types.ts
  src/util/align.ts
  tests/unit/legend/category-spec.ts
  tests/unit/tooltip/html-spec.ts
Labels: PR: reviewed-approved, enhancement

#148 chore: update scale version
  package.json
Labels: PR: reviewed-approved, chore

#149 test(legend): test offset
  tests/unit/legend/category-spec.ts
Labels: PR: unreviewed, test

#151 feat(capture): add capture to all component
  README.md
  package.json
  src/abstract/component.ts
  src/abstract/group-component.ts
  src/abstract/html-component.ts
  src/interfaces.ts
  src/legend/category.ts
  src/types.ts
  tests/unit/component/component-spec.ts
  tests/unit/component/group-simple-spec.ts
  tests/unit/component/html-component-spec.ts
Labels: PR: unreviewed, enhancement

#155 Fix constructor error
  package.json
  src/axis/grid.js
  src/legend/slider.js
Labels: PR: reviewed-changes-requested
